export default {
	VITE_BACKEND_URL: import.meta.env.VITE_BACKEND_URL || 'http://localhost:4000',
	VITE_SERVER_IO: import.meta.env.VITE_SERVER_IO || 'http://localhost:4000',
	VITE_PRIMARY_COLOR: '#0284C7',
	VITE_SECONDARY_COLOR: '#41A0D0',
	VITE_TERTIARY_COLOR: '#013047',
	VITE_DANGER_COLOR: '#e93553',
	VITE_WARNING_COLOR: '#ffce7a',
	VITE_SUCCESS_COLOR: '#16ca91',
	VITE_INFO_COLOR: '#62b7f4',
	VITE_LIGHT_COLOR: '#F3F4F6',
	VITE_DARK_COLOR: '#1B2831',
	VITE_NEUTRAL_COLOR: '#b7c1c8',
};
